// Fluxle daily word schedule
// FLUXLE_PUZZLES[0] = launch day (2026-05-15) = puzzle #1
// List covers 200 days; cycles after that
//
// Hives puzzles are procedurally generated each day from:
//   seed = (YYYYMMDD) * 10 + dayOfWeek
// No manual database needed — every date has a unique, deterministic puzzle.

window.FLUXLE_PUZZLES = [
  // Days 1-82 — original sequence
  'DRIFT','LIGHT','POWER','SHIFT','SPARK','SPEED','WATER','BLAST','CARRY','CRAFT',
  'DEPTH','FLARE','FROST','GLINT','GRACE','GRAND','GRIND','HOVER','INERT','JOINT',
  'KNEEL','LATCH','LEVER','MERCY','NORTH','ORBIT','PIVOT','PLAIN','PRIME','REACH',
  'RIGID','ROVER','STARK','STERN','STIFF','STING','SWEPT','SWIFT','THICK','THINK',
  'THIRD','TIGHT','TREAD','TRUST','TWICE','TWIRL','BLUNT','PULSE','FLINT','CRISP',
  'BRISK','STOMP','CLEFT','PLUCK','STRUT','SPURT','CREPT','SKILL','CLOTH','FLESH',
  'DRIVE','FLAME','HEART','MUSIC','NIGHT','OCEAN','RIVER','STONE','TRAIL','VAPOR',
  'BLEND','CHART','INPUT','KARMA','PLUME','ULTRA','WIDTH','YIELD','PLANT','BRAVE',
  'CLOCK','BRUSH',
  // Days 83-200 — extended schedule
  'FORCE','FIELD','DENSE','LASER','PRISM','QUARK','RADAR','SOLAR','TIDAL','DELTA',
  'GAMMA','ALPHA','FLASH','FLUID','SIGMA','THETA','OMEGA','CHAIN','DECAY','FOCUS',
  'FORGE','GLIDE','HELIX','JOULE','LUMEN','MODEL','MOLAR','MOTOR','NEXUS','NOBLE',
  'NOISE','OXIDE','OZONE','PHASE','PHOTO','PILOT','POLAR','PROBE','RATIO','RELAY',
  'REPEL','RESET','ROTOR','SCALE','SCOPE','SHEAR','SHOCK','SLOPE','SOLID','SONIC',
  'SPACE','SPLIT','SPRAY','STEEL','STEEP','STORM','SURGE','SWARM','SWEEP','SWELL',
  'SWING','SWIRL','TESLA','TRACE','TRACK','TREND','TRUSS','TUNER','TWEAK','TWIST',
  'UMBRA','UNITY','VALVE','WEDGE','WHIRL','WHOLE','WIELD','XENON','FIBER','GRAIN',
  'GRADE','GRAPH','LUNAR','METAL','MERGE','REALM','RADON','RIVET','ROUND','ROUTE',
  'VALID','VITAL','VOCAL','WEIRD','WINCH','EXACT','EXPEL','EPOCH','ERODE','EVOKE',
  'EXCEL','EXILE','FANCY','FETCH','FLAIR','FLASK','FLECK','FLICK','FLOCK','FLOOD',
  'FLUKE','FLUSH','FOCAL','FORAY','FROWN','GAUGE','GLAND','GLARE'
];
